### PR TITLE
Fix placeholder position check 

### LINKED ISSUE #883: Duplicate Child Comments
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1 (100)

### Where did you get the app from

Google Play

### Android version

10

### Device model

TECNO KE7

### First occurred

Idk probably about some weeks ago

### Steps to reproduce

1. Open post
2. Go through comments
3. Open child comments
4. Then the child comments are duplicated

Screenshot_20220802-112357

### Expected behaviour

The child comments should not be duplicate

### Current behaviour

Duplicate child comments

### Logs

No, the app dom't crash for me ever

### PR DESCRIPTION
**Pull request by RSBat**
Found this while working on a refactoring I mentioned in another pr

Fixes #883 

- [Fix placeholder position check](https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/a880f9b332f7e94a435cc69f215e4d70714f9f1f)

  Because of the missed negation `placeholderPosition` could actually point to a different comment. As a result loaded comments would be displayed at a wrong position which could result in duplicated comments.

- [Extract placeholder search code](https://github.com/Docile-Alligator/Infinity-For-Reddit/commit/a69a5ca1574875c56513d40164300d0110d8c251)

  Simple refactoring. The only notable change is that now technically `placeholderPosition` can be -1. In practice that should never happen, but I added checks anyways

### CODE REVIEW

File: app/src/main/java/ml/docilealligator/infinityforreddit/adapters/CommentsRecyclerViewAdapter.java [hunk 1]
```diff
@@ -736,17 +716,9 @@ public void onFetchMoreCommentFailed() {
...
-                                                    for (int i = parentPosition + 1; i < mVisibleComments.size(); i++) {
-                                                        if (mVisibleComments.get(i).getFullName().equals(parentComment.getFullName())) {
-                                                            placeholderPosition = i;
-                                                            break;
-                                                        }
-                                                    }
-                                                }
+                                                int placeholderPosition = findLoadMoreCommentsPlaceholderPosition(parentComment.getFullName(), commentPosition);
 
-                                                if (placeholderPosition >= mVisibleComments.size() || placeholderPosition < 0) {
```
Comment (Docile-Alligator) [inline app/src/main/java/ml/docilealligator/infinityforreddit/adapters/CommentsRecyclerViewAdapter.java:749]: Is it a bug? `placeholderPosition >= mVisibleComments.size() || placeholderPosition < 0` does not make any sense haha.

Comment (RSBat) [reply app/src/main/java/ml/docilealligator/infinityforreddit/adapters/CommentsRecyclerViewAdapter.java:749]: Yes, it should've been inverted. Fortunately that condition was always false because of the search above.
Now you'd think that it wouldn't update the button, but the text is updated unconditionally outside the check. This is a separate problem because holder can get bound to another placeholder by the time callback is triggered.

The only thing I don't understand here is why `mVisibleComments.get(placeholderPosition)` is not the same object as `mVisibleComments.get(parentPosition).getChildren().get(mVisibleComments.get(parentPosition).getChildren().size() - 1)`. Because scrolling up and down changes button's text back to "Loading". But then collapsing and expanding parent comment correctly displays "loading failed". So it means we have two Comment objects that represent the same placeholder that got out of sync.

However that's not all! If you repeat above steps again with the same comment, it will display "loading failed" after scrolling. So the two objects are now the same object! At least this is expected, because that's what `expandComments` should do. Why this isn't the case after initial load? No idea.

**Comment by Docile-Alligator** [comment]
Thank you!
