### PR TITLE
Remember paused state for autoplay videos

### LINKED ISSUE #1325: Paused videos continue after slight scroll
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.4.0-beta1

### Where did you get the app from

Google Play

### Android version

Android 11

### Device model

OnePlus 7T

### First occurred

Unknown

### Steps to reproduce

1. Play a video in the feed
2. Pause it
3. Make a slight scroll
4. The paused video unpauses itself for no reason

### Example post, link, markdown...

Any video in your feed

### Expected behaviour

Paused videos should stay paused no matter what

### Current behaviour

Paused videos seem to not realize when to be unpaused

### Logs

_No response_

### PR DESCRIPTION
**Pull request by scria1000**
While on feed, a manually paused autoplay video will stay paused as long as the video is not completely out of sight (then it will reset).
Inside a post, a manually paused video will stay paused even if the user scrolls out of view.

resolves #1325

### CODE REVIEW

File: app/src/main/java/ml/docilealligator/infinityforreddit/adapters/HistoryPostRecyclerViewAdapter.java [hunk 1]
```diff
@@ -2853,11 +2907,24 @@ public void release() {
...
+            container = null;
         }
 
         @Override
         public boolean wantsToPlay() {
-            return canPlayVideo && mediaUri != null && ToroUtil.visibleAreaOffset(this, itemView.getParent()) >= mStartAutoplayVisibleAreaOffset;
+            if (canPlayVideo) {
+                if (ToroUtil.visibleAreaOffset(this, itemView.getParent()) >= mStartAutoplayVisibleAreaOffset) {
+                    if (isManuallyPaused) {
+                        play();
```
Comment (Docile-Alligator) [inline app/src/main/java/ml/docilealligator/infinityforreddit/adapters/HistoryPostRecyclerViewAdapter.java:2919]: Why is `play()` needed here?

File: app/src/main/java/ml/docilealligator/infinityforreddit/adapters/PostRecyclerViewAdapter.java [hunk 2]
```diff
@@ -4611,6 +4687,36 @@ class PostCard2VideoAutoplayViewHolder extends PostBaseViewHolder implements Tor
...
+
+                @Override
+                public void onScrubMove(TimeBar timeBar, long position) {
+
+                }
+
+                @Override
+                public void onScrubStop(TimeBar timeBar, long position, boolean canceled) {
+                    if (!canceled) {
+                        savePlaybackInfo(getPlayerOrder(), getCurrentPlaybackInfo());
```
[the remark this answers is not in the document]
Comment (scria1000) [reply app/src/main/java/ml/docilealligator/infinityforreddit/adapters/PostRecyclerViewAdapter.java:4715]: For some reason, Playback will resume from the cached PlaybackInfo if you change the playback position while the video is paused and only half visible.

File: app/src/main/java/ml/docilealligator/infinityforreddit/adapters/HistoryPostRecyclerViewAdapter.java (hunk 1 above)
Comment (scria1000) [reply app/src/main/java/ml/docilealligator/infinityforreddit/adapters/HistoryPostRecyclerViewAdapter.java]: Without it, helper.setVolume causes a crash after a release() (say when when you scroll the player out of view), I think it's because play() makes some initializations.

**Comment by Docile-Alligator** [comment]
Thank you!
