### PR TITLE
Heading markdown fix

### LINKED ISSUE #901: Space is added after # in code blocks
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1

### Where did you get the app from

Google Play

### Android version

12

### Device model

_No response_

### First occurred

_No response_

### Steps to reproduce

Open anything with the following markdown
```
    hello
    #hello
```

### Expected behaviour

Displays as 
```
hello
#hello
```

### Current behaviour

Displays as 
```
hello
# hello
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by RSBat**
Previously space after # was fixed by applying regex to everything. This also changed text inside code blocks, which are supposed to stay intact. This is impossible to do with only regex so I'm modifying the parser.

Headings parsing logic is not overridable in the class, so I just copied it and added comments.

The fix works and I hope I've applied it everywhere it should be applied. Also I've found two cases when plugins were not applied when responding to post or comment.

Fixes #901

### CODE REVIEW

File: app/src/main/java/ml/docilealligator/infinityforreddit/activities/CommentActivity.java [hunk 1]
```diff
@@ -233,6 +235,8 @@ public void configureTheme(@NonNull MarkwonTheme.Builder builder) {
                     }
                 })
                 .usePlugin(SpoilerParserPlugin.create(commentColor, commentSpoilerBackgroundColor))
+                .usePlugin(RedditHeadingPlugin.create())
+                .usePlugin(StrikethroughPlugin.create())
```
Comment (RSBat) [inline app/src/main/java/ml/docilealligator/infinityforreddit/activities/CommentActivity.java:239]: I did a bit more digging/testing and found out that this is applied to both comments which should be parsed and post titles which shouldn't (at least not for spoilers, headings and strikethrough)

So this both fixes and breaks stuff, even if only minor.

**Comment by Docile-Alligator** [comment]
Thank you very much!
